# ======================
# Application
# ======================
quarkus.application.name=my-processor

# ======================
# HTTP
# ======================
quarkus.http.port=8084

# ======================
# Logging
# ======================
quarkus.log.level=INFO
quarkus.log.category."org.rayshan".level=DEBUG

#datasource
filepush.datasource.name=${DATA_SOURCE:test2}

# ======================
# Kafka — disable Dev Services so Quarkus does NOT try to
# spin up / connect to a real broker on startup in dev mode.
# Replace the bootstrap-servers value with your real broker when ready.
# ======================
quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=localhost:9092
# earliest/latest
app.config.kafka.offset-reset=earliest

# Tell the Camel Kafka component where the broker is
camel.component.kafka.brokers=localhost:9092

# Output Kafka topic
app.config.kafka.output-topic=test-out-topic
app.config.kafka.output-topic-prefix=file.processed

# ======================
# AWS S3 — dummy values to prevent SDK from blocking startup
# ======================
#quarkus.camel.aws2-s3.access-key=dummy
#quarkus.camel.aws2-s3.secret-key=dummy
#quarkus.camel.aws2-s3.region=us-east-1

#S3 config
app.config.s3.endpoint=${S3_END_POINT:http://localhost:9000}
app.config.s3.bucket-name=${S3_BUCKET_NAME:file-push-test-src}
app.config.s3.region=${S3_REGION:us-east-1}
app.config.s3.access-key=${S3_ACCESS_KEY:admin}
app.config.s3.secret-key=${S3_SECRET_KEY:password123}

# ======================
# Health
# ======================
quarkus.smallrye-health.root-path=/health

# ======================
# Whitelist REST Client
# ======================
quarkus.rest-client."whitelist-client".url=http://localhost:3000
quarkus.rest-client."whitelist-client".scope=jakarta.inject.Singleton

# Register model classes for reflection (needed for RestClient proxy in async threads)
quarkus.reflection.classes=org.rayshan.processor.model.WhitelistResponse,org.rayshan.processor.model.WhitelistData,org.rayshan.processor.client.WhitelistClient
quarkus.reflection.serializable-types=org.rayshan.processor.model.WhitelistResponse,org.rayshan.processor.model.WhitelistData
